name: Terraform CI/CD (lab-tf-102-mod-remote)

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lab-tf-102-mod-remote/**"
      - ".github/workflows/terraform.yml"
  push:
    branches: [ "main" ]
    paths:
      - "lab-tf-102-mod-remote/**"
      - ".github/workflows/terraform.yml"

permissions:
  contents: read

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_VERSION: "1.6.6"

jobs:
  plan:
    # Chỉ chạy khi là pull_request (tránh cần thêm Branch Credential cho main)
    if: github.event_name == 'pull_request'
    name: PR – fmt/validate/plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write         # cần cho OIDC
      contents: read
    defaults:
      run:
        working-directory: lab-tf-102-mod-remote
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: terraform init (Backend via AAD)
        run: terraform init -reconfigure

      - name: terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan -no-color -out=tfplan

      - name: Export plan
        run: terraform show -no-color tfplan > plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan-${{ github.run_id }}
          path: lab-tf-102-mod-remote/plan.txt

  apply:
    name: main – apply (mit Approval)
    needs: plan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: lab                # PHẢI trùng y hệt Environment trong repo
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: lab-tf-102-mod-remote
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: terraform init
        run: terraform init -reconfigure

      - name: terraform plan (again for apply)
        run: terraform plan -no-color -out=tfplan

      - name: terraform apply
        run: terraform apply -auto-approve tfplan
